# searx:
#   #network_mode: "bridge"
#   #  build:
#     #6  context: /path/to/searx
#     #    dockerfile: Dockerfile
#   image: searx
#   container_name: searx
#   ports:
#      - "8088:8088"
#   environment:
#     - BASE_URL="https://domain.tld"
#     - IMAGE_PROXY=True
#   # command: './run.sh'
#   volumes:
#     - './run.sh:/run.sh'
#       #  command: './run.sh'

version: '2'
services:
    searx:
        image: wonderfall/searx
        container_name: searx
        ports:
          - "8888:8888"
