#!/bin/bash
#accessX needed
#stickykeys -stickytwokeydisable
ax -timeout   +mousekeys mousedelay 1 mouseinterval 10 mousetimetomax 52 mousemaxspeed 30 +repeatkeys repeatdelay 500 repeatinterval 20 +stickykeys -stickytwokeydisable +stickylatchtolock
